### ISSUE TITLE
YOLO algorithm on Videos

### ISSUE THREAD

**Issue by MasDrago** [JudasDie/deepleraning.ai-course#14]
In week 3 content of CNN's course, we applied YOLO algorithm for predicting bounding boxes on images. How can we apply the same for videos.

**Comment by iamsurya** [comment]
Apply it to every frame.

**Comment by MasDrago** [comment]
I changed the tensorflow v1 implementation to tensorflow v2. Then used OpenCV's Videowriter for prediction on every frame of Video.
